name: Build VerChk

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build
      run: ./gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: verchk-${{github.sha}}
        path: build/distributions/vsosh-verchk*.tar
